import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/app/providers/ThemeProvider";
import ReactQueryProvider from "../providers/ReactQueryProvider";
import Header from "../components/Header";
import { getDictionary } from "../lib/dictionaries";
import { Locale } from "../lib/i18n-config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const t = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body>
        <ThemeProvider>
          <ReactQueryProvider>
            <Header welcomeMessage={t.welcome} themeLabels={t.theme} />
            <main className="max-w-4xl mx-auto px-4 py-6">{children}</main>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
